version: '3.4'

services:
  angcliapp:
    image: angcliapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 44440:44440
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
