products:
  - id: 1
    name: "TVS Sport"
    description: "Powered by a 109.7cc, single-cylinder, air-cooled engine, TVS Sport BS6 offers a Behtareen mileage It provides 15% more mileage with its  ETFI Technology. The engine is tuned to offer a balance of power and fuel efficiency, making it an ideal choice for daily commuting."
    price: 84300
    cc: 110
    torque: 8.7
    torqueRpm: 4500
    maxPower: 6.03
    maxPowerRpm: 7350
    speed: 90
    gear: 4
    tankCapacity: 10
    isHidden: false
    buyUrl: "https://www.tvsmotor.com/book-online/select-variant?tvs-sport"
    image: https://www.tvsmotor.com/tvs-sport/-/media/Brand-Pages-Webp/Sport-optimised-image-700x500/900x500_Black/12.png

  - id: 2
    name: "Radeon"
    description: "Read more about TVS Radeon specifications and features such as mileage, 109.7cc engine, 10L fuel tank capacity, and other technical specs."
    price: 89544
    cc: 110
    torque: 8.7
    torqueRpm: 4500
    maxPower: 6.03
    maxPowerRpm: 7350
    speed: 90
    gear: 4
    tankCapacity: 10
    isHidden: false
    buyUrl: "https://www.tvsmotor.com/book-online/select-variant?radeon"
    image: https://www.tvsmotor.com/tvs-radeon/-/media/Brand-Pages-Webp/Radeon/web/360/DIGI-Cluster/DT-Blue-Black/16.png

  - id: 3
    name: "Raider"
    description: "Go wicked with distinct sporty styling, best in class performance and high-tech advanced features"
    price: 109559
    cc: 125
    torque: 11.2
    torqueRpm: 6000
    maxPower: 8.37
    maxPowerRpm: 7500
    speed: 110
    gear: 5
    tankCapacity: 10
    isHidden: false
    buyUrl: "https://www.tvsmotor.com/book-online/select-variant?tvs-raider"
    image: https://www.tvsmotor.com/tvs-raider/-/media/TVSv2/Brand-Pages/Raider2/360View/SmartXonnect/Yellow-SX/19.webp

  - id: 4
    name: "TVS Star City Plus"
    description: "TVS Star City Plus is the only bike in the 110cc segment to have LED Tech Headlamp. It comes with a metallic bezel which enhances your style quotient and is energy efficient (3x more brightness with 67% less power consumption)"
    price: 91649
    cc: 110
    torque: 8.7
    torqueRpm: 4500
    maxPower: 6.03
    maxPowerRpm: 7350
    speed: 90
    gear: 4
    tankCapacity: 10
    isHidden: false
    buyUrl: "https://www.tvsmotor.com/book-online/select-variant?tvs-star-city-plus"
    image: https://www.tvsmotor.com/tvs-star-city-plus/-/media/Brand-Pages/TVSStarCity/Colour/Black-Red-Disc/12.png

  - id: 5
    name: "TVS Ronin"
    description: "TVS Star City Plus is the only bike in the 110cc segment to have LED Tech Headlamp. It comes with a metallic bezel which enhances your style quotient and is energy efficient (3x more brightness with 67% less power consumption)"
    price: 178626
    cc: 226
    torque: 19.93
    torqueRpm: 3750
    maxPower: 15.01 
    maxPowerRpm: 7750
    speed: 120
    gear: 5
    tankCapacity: 14
    isHidden: false
    buyUrl: "https://www.tvsmotor.com/book-online/select-variant?tvs-ronin"
    image: https://www.tvsmotor.com/tvs-ronin/-/media/U368Media/Images/LandingPage/Configurator/configurator-bike.png?la=en&h=448&w=749&hash=D858C19D82782BF8B6AA9F29553CAF53

  - id: 6
    name: "Apache RTR 160"
    description: "For over ten years the TVS Apache RTR 160 has been a mainstay on the track, pushing the boundaries of performance"
    price: 147240
    cc: 160
    torque: 13.85
    torqueRpm: 7000
    maxPower: 11.8
    maxPowerRpm: 8750
    speed: 107
    gear: 5
    tankCapacity: 12
    isHidden: false
    buyUrl: "https://www.tvsmotor.com/book-online/select-variant?apache-rtr-160-2v"
    image: https://www.tvsmotor.com/tvs-apache/-/media/apache_160_2v_new_addition/price_desktop_new.webp

  - id: 7
    name: "TVS Apache RTR 200 4V"
    description: "For over ten years the TVS Apache RTR 160 has been a mainstay on the track, pushing the boundaries of performance"
    price: 190571
    cc: 198
    torque: 17.25
    torqueRpm: 7250
    maxPower: 15.32
    maxPowerRpm: 9000
    speed: 127
    gear: 5
    tankCapacity: 12
    isHidden: false
    buyUrl: "https://www.tvsmotor.com/book-online/select-variant?apache-rtr-200-4v"
    image: https://www.tvsmotor.com/tvs-apache/-/media/Brand-Pages/Apache/Apache-RTR/APACHE-RTR-200-4V-1Ch-ABS/Concept/webp-images/Apache-200-4V--Profile-Shot---977-x-644-Pix.webp

  - id: 8
    name: "Hornet 2"
    description: "The all-new Hornet 2.0 is all about letting people live their dream. The fierce machine keeps you ahead of others. It is a manifestation of style, safety and power. It turns heads and converts the road into a steady blur in seconds. It’s pure exhilaration at a flick of your wrist."
    price: 180968
    cc: 185
    torque: 15.9  
    torqueRpm: 6000
    maxPower: 12.7
    maxPowerRpm: 8500
    speed: 127
    gear: 5
    tankCapacity: 12
    isHidden: false
    buyUrl: "https://www.honda2wheelersindia.com/BookNow?Hornet2-0"
    image: https://www.honda2wheelersindia.com/assets/images/CBHornetBS_6/360/24.png

  - id: 9
    name: "SP 160"
    description: "The all-new Hornet 2.0 is all about letting people live their dream. The fierce machine keeps you ahead of others. It is a manifestation of style, safety and power. It turns heads and converts the road into a steady blur in seconds. It’s pure exhilaration at a flick of your wrist."
    price: 154853
    cc: 163
    torque: 14.58
    torqueRpm: 5500
    maxPower: 9.9
    maxPowerRpm: 7500
    speed: 110
    gear: 5
    tankCapacity: 12
    isHidden: false
    buyUrl: "https://www.honda2wheelersindia.com/BookNow?sp-160"
    image: https://www.honda2wheelersindia.com/assets/images/sp160/gallery_sp160/24.png

  - id: 10
    name: "Triumph Speed 400"
    description: "Born into a peerless bloodline, the Speed 400 has Triumph’s unique Modern Classic roadster design in its DNA."
    price: 292931
    cc: 399
    torque: 37.5
    torqueRpm: 6500
    maxPower: 29.4
    maxPowerRpm: 8000
    speed: 160
    gear: 6
    tankCapacity: 13
    isHidden: false
    buyUrl: "https://www.triumphmotorcyclesindia.com/booking/speed-400"
    image: https://www.triumphmotorcyclesindia.com/images/404/bike-img.png

  - id: 11
    name: "Bajaj Pulsar 150"
    description: "The bike now comes with striking new graphics, carbon fibre accents and iconic wolf-eyed headlamps. Everything on this icon gets noticed! "
    price: 138125
    cc: 150
    torque: 13.25
    torqueRpm: 6500
    maxPower: 10.3
    maxPowerRpm: 8500
    speed: 110
    gear: 4
    tankCapacity: 15
    isHidden: false
    buyUrl: "https://www.bajajauto.com/bikes/pulsar/pulsar-150"
    image: https://cdn.bajajauto.com/-/media/assets/bajajauto/bikes/pulsar-150-2024/150-feat/safe-d.png

  - id: 12
    name: "Bajaj Pulsar 220F"
    description: "The bike now comes with striking new graphics, carbon fibre accents and iconic wolf-eyed headlamps. Everything on this icon gets noticed! "
    price: 171840
    cc: 220
    torque: 18.55
    torqueRpm: 7000
    maxPower: 15
    maxPowerRpm: 8500
    speed: 134
    gear: 5
    tankCapacity: 15
    isHidden: false
    buyUrl: "https://www.bajajauto.com/bikes/pulsar/pulsar-220f"
    image: https://cdn.bajajauto.com/-/media/assets/bajajauto/bikes/pulsar-220f-2024/360-degree/web/blue/00.png

  - id: 13
    name: "Bajaj Platina 100"
    description: "The powerful DTS-i engine is designed to deliver unmatched performance and superior mileage. "
    price: 80657
    cc: 102
    torque: 8.3
    torqueRpm: 5500
    maxPower: 5.8
    maxPowerRpm: 7500
    speed: 90
    gear: 4
    tankCapacity: 11
    isHidden: false
    buyUrl: "https://www.bajajauto.com/bikes/platina/platina-100"
    image: https://cdn.bajajauto.com/-/media/assets/bajajauto/360degreeimages/bikes/platina/platina-100es-ebony-black-red/00.png

  - id: 14
    name: "Yamaha FZ FI"
    description: "The powerful DTS-i engine is designed to deliver unmatched performance and superior mileage. "
    price: 132820
    cc: 149
    torque: 13.3
    torqueRpm: 5500
    maxPower: 9.1 
    maxPowerRpm: 7250
    speed: 115
    gear: 5
    tankCapacity: 13
    isHidden: false
    buyUrl: "https://shop.yamaha-motor-india.com/products/fz-fi-new-1"
    image: https://www.yamaha-motor-india.com/theme/v4/images/webp_images/fz_series_all/fz-fi/color/cyan.webp

  - id: 15
    name: "Splendor Plus"
    description: "The powerful DTS-i engine is designed to deliver unmatched performance and superior mileage. "
    price: 89201
    cc: 98
    torque: 8.05
    torqueRpm: 6000
    maxPower: 5.9
    maxPowerRpm: 8000
    speed: 90
    gear: 4
    tankCapacity: 9.8
    isHidden: false
    buyUrl: "https://www.heromotocorp.com/en-in/motorcycles/practical/splendor-plus.html"
    image: https://www.heromotocorp.com/content/dam/hero-commerce/in/en/products/practical/splendor-plus/HSPPPDRSCFIRPB/360/1.png

  - id: 16
    name: "HF 100"
    description: "The powerful DTS-i engine is designed to deliver unmatched performance and superior mileage. "
    price: 58999
    cc: 98
    torque: 8.05
    torqueRpm: 6000
    maxPower: 5.9
    maxPowerRpm: 8000
    speed: 85
    gear: 4
    tankCapacity: 9.1
    isHidden: false
    buyUrl: https://www.heromotocorp.com/en-in/motorcycles/practical/hf-100.html
    image: https://www.heromotocorp.com/content/dam/hero-commerce/in/en/products/practical/hf-100/HHNDJDRKCFIRBK/360/1.png

  - id: 17
    name: "Xtreme 125R"
    description: "Single-channel ABS, LED lights, lightweight chassis"
    price: 132602
    cc: 125
    torque: 10.5
    torqueRpm: 6500
    maxPower: 11.4
    maxPowerRpm: 8250
    speed: 100
    gear: 5
    tankCapacity: 10
    isHidden: false
    buyUrl: https://www.heromotocorp.com/en-in/motorcycles/performance/xtreme-125r.html
    image: https://www.heromotocorp.com/content/dam/hero-commerce/in/en/products/performance/content-fragments/xtreme-125r/assets/redesign/Xtreme-125R-Full-Web-2x.png

  - id: 18
    name: "Hero Xtreme 160R"
    description: "Full-LED setup, hazard lights, sporty design"
    price: 128374
    cc: 164
    torque: 14.6
    torqueRpm: 6500
    maxPower: 14.79
    maxPowerRpm: 8500
    speed: 115
    gear: 5
    tankCapacity: 12
    isHidden: false
    buyUrl: https://www.heromotocorp.com/en-in/motorcycles/performance/xtreme-160r.html
    image: https://www.heromotocorp.com/content/dam/hero-commerce/in/en/products/performance/xtreme-160r/HXTRWDSSCFIMGB/360/1.png

  - id: 19
    name: "Xtreme 200S 4V"
    description: "Tubeless tyres, 4V engine, sporty design"
    price: 143442
    cc: 200
    torque: 16.9
    torqueRpm: 8500
    maxPower: 16.6
    maxPowerRpm: 8500
    speed: 130
    gear: 5
    tankCapacity: 12
    isHidden: false
    buyUrl: https://www.heromotocorp.com/en-in/motorcycles/performance/xtreme-200s-4v.html
    image: https://www.heromotocorp.com/content/dam/hero-commerce/in/en/products/performance/xtreme-200s-4v/HEXTDADSCFIPBK/360/1.png

  - id: 20
    name: "Hero Xtreme 160R 4V"
    description: "High ground clearance, powerful engine"
    price: 160924
    cc: 164
    torque: 14.6
    torqueRpm: 6500
    maxPower: 16.9
    maxPowerRpm: 8500
    speed: 140
    gear: 5
    tankCapacity: 12
    isHidden: false
    buyUrl: https://www.heromotocorp.com/en-in/motorcycles/performance/xtreme-160r-4v.html
    image: https://www.heromotocorp.com/content/dam/hero-commerce/in/en/products/performance/xtreme-160r-4v/HXTMEPDSCFIABM/360/1.png

  - id: 21
    name: "Karizma XMR 210"
    description: "Advanced features, sporty design"
    price: 228775
    cc: 210
    torque: 20.4
    torqueRpm: 7250
    maxPower: 25.5
    maxPowerRpm: 9250
    speed: 135
    gear: 6
    tankCapacity: 12
    isHidden: false
    buyUrl: https://www.heromotocorp.com/en-in/motorcycles/practical/hf-100.html
    image: https://www.heromotocorp.com/content/dam/hero-aem-website/in/en-in/premia/acaa/product-detail/360/360-images/yellow-2/01.png
